---
title: "Marine-Model-Project"
output: html_document
---

```         

The Harvest Ratio is the proportion of instantaneous biomass captured per unit time. It is calculated by both Activity and Power of the fishing gear.

The initial Goal of the project was to create a program that calculates the required Activity multiplier for a specific input target harvest ratio.

```

```{r setup, message = FALSE}

# results = 'hide'

library(StrathE2E2)
model <- e2e_read("North_Sea","2003-2013")
results <- e2e_run(model,nyears=3)

# library(rootSolve)
library(lpSolve)

source("functions.R")

```

```{r}

Target_Harvest_Ratio <- c(0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05)

Activity <- model$data$fleet.model$gear_activity
Power <- model$data$fleet.model$gear_group_rel_power
Activity_Multiplier <- model$data$fleet.model$gear_mult


# Power_m <- as.matrix(Power)
# 
# HR <- Activity * Power
# HR_m <-  Activity %*% Power_m


Harvest_Ratio <- e2e_extract_hr(model,results)
# HR <- F_calc_func(model, results)


```

```{r}

F_calc_func <- function(basemodel,dataset) {
  
  model<-basemodel
  fishing_fleet_model<-StrathE2E2:::fishing_fleet_model
  
  shallowprop<-sum(model$data$physical.parameters$habitat_areas[1:4])
  deepprop_exOH<-sum(model$data$physical.parameters$habitat_areas[5:8])
  
  grouplabels <- c(
    "Planktivorous_fish",
    "Demersal_fish",
    "Migratory_fish",
    "Benthos_susp-dep",
    "Benthos_carn-scav",
    "Zooplankton_carn",
    "Birds",
    "Pinnipeds",
    "Cetaceans",
    "Macrophytes"
  )
  
  fleet_object <- fishing_fleet_model(model,2)
  
  fleet_vector	<- fleet_object$fleet_vector
  
  zonalHRs<-data.frame(Guilds=grouplabels,Inshore_harvest_ratio=rep(0,length(grouplabels)),Offshore_harvest_ratio=rep(0,length(grouplabels)),Whole_domain_harvest_ratio=rep(0,length(grouplabels)))
  
  zonalHRs$Inshore_harvest_ratio<-c(fleet_vector["F_inshore_pelagic"],
                                    fleet_vector["F_inshore_demersal"],
                                    fleet_vector["F_inshore_migratory"],
                                    fleet_vector["F_inshore_filtben"],
                                    fleet_vector["F_inshore_carnben"],
                                    fleet_vector["F_inshore_carnzoo"],
                                    fleet_vector["F_inshore_bird"],
                                    fleet_vector["F_inshore_seal"],
                                    fleet_vector["F_inshore_ceta"],
                                    fleet_vector["F_inshore_kelp"])
  
  zonalHRs$Offshore_harvest_ratio<-c(fleet_vector["F_offshore_pelagic"],
                                     fleet_vector["F_offshore_demersal"],
                                     fleet_vector["F_offshore_migratory"],
                                     fleet_vector["F_offshore_filtben"],
                                     fleet_vector["F_offshore_carnben"],
                                     fleet_vector["F_offshore_carnzoo"],
                                     fleet_vector["F_offshore_bird"],
                                     fleet_vector["F_offshore_seal"],
                                     fleet_vector["F_offshore_ceta"],
                                     fleet_vector["F_offshore_kelp"])
  
  zonalHRs$Whole_domain_harvest_ratio[c(1,2,3,6,7,8,9)]<- (zonalHRs$Inshore_harvest_ratio[c(1,2,3,6,7,8,9)]*shallowprop) + (zonalHRs$Offshore_harvest_ratio[c(1,2,3,6,7,8,9)]*(1-shallowprop))
  zonalHRs$Whole_domain_harvest_ratio[c(4,5,10)]<- ((zonalHRs$Inshore_harvest_ratio[c(4,5,10)]*shallowprop) + (zonalHRs$Offshore_harvest_ratio[c(4,5,10)]*(deepprop_exOH)))/(shallowprop+deepprop_exOH)
  
  return(zonalHRs)
  
}

```

```{r}

# Extracts all non-zero entries in the power data frame
extract_nonzero_power <- function(power_data_frame) {
  
  # ensures power is a matrix
  power_matrix <- as.matrix(power_data_frame)
  
  # find non-zero entries, idx = index
  idx <- which(power_matrix != 0, arr.ind = TRUE)
  
  # builds the data frame, df = data frame
  df <- data.frame(
    Guild = idx[, 2],
    Gear = idx[, 1],
    Power_Value = power_matrix[idx]
  )
  
  return(df)
}


extract_single_guild_occurrence <- function(df) {
  
  # count how many times each column appears
  guild_counts <- table(df$Guild)
  
  # find columns that appear exactly once
  single_guild <- names(guild_counts[guild_counts == 1])
  
  # filter original data frame
  single_guild_df <- df[df$Guild %in% as.numeric(single_guild), ]
  
  return(single_guild_df)
}


edit_single_activity_multiplier <- function(single_guild_df, target_HR, harvest_ratio_data, target_Activity) {
  
  index_guild <- single_guild_df$Guild
  index_gear <- single_guild_df$Gear
  
  target_Activity[index_gear] <- target_HR[index_guild] / harvest_ratio_data$Whole_domain_harvest_ratio[index_guild]
  
  return(target_Activity)
}


find_HR_components <- function(target_activity, model) {
  
  temp_model <- model
  
  temp_activity <- rep(0, 12)
  temp_activity[target_activity] <- 1
  
  temp_model$data$fleet.model$gear_mult <- temp_activity
  temp_results <- e2e_run(temp_model,nyears=3)
  harvest_ratio_component <- e2e_extract_hr(temp_model,temp_results)
  
  return(harvest_ratio_component)
}



#########################
modify_targer_HR <- function(df, single_guild_df, target_HR, model) {
  
  
  for (i in seq_along(length(single_guild_df$Gear))) {
   
    harvest_ratio_data <- find_HR_components(single_guild_df$Gear[i], model)
    
    guild_idx <- df$Guild[df$Gear == single_guild_df$Gear[i]]

    target_HR[guild_idx] <- target_HR[guild_idx] - harvest_ratio_data$Whole_domain_harvest_ratio[guild_idx]
    
  }
  return(target_HR)
}
############################



filter_gear <- function(df, filter_df) {
  df <- df[!(df$Gear %in% filter_df), ]
  return(df)
}



normalize_power_by_group_max <- function(df) {
  
  # get max per column group
  max_vals <- tapply(df$Power_Value, df$Guild, max)
  
  # map max back to each row
  df$MaxValue <- max_vals[as.character(df$Guild)]
  
  # normalize (maxP/currentP)
  df$Normalized <- df$MaxValue / df$Power_Value
  
  return(df)
}



find_simultaneous_equations <- function(df) {
  
  unique_sorted <- sort(unique(df$Gear))
  
  res_list <- lapply(unique_sorted, function(v) {
    out <- find_HR_components(v, model)
    out$Whole_domain_harvest_ratio
  })

  
  mat <- do.call(cbind, res_list)
  
  return(mat)
}


```

```{r include=FALSE}



df <- extract_nonzero_power(Power)

repeat {
  single_guild_df <- extract_single_guild_occurrence(df)

  if (nrow(single_guild_df) == 0) {
    break
  }
  
  new_gear_mults <- edit_single_activity_multiplier(single_guild_df, Target_Harvest_Ratio, Harvest_Ratio, Activity_Multiplier)
  Target_Harvest_Ratio <- modify_targer_HR(df, single_guild_df, Target_Harvest_Ratio, model)
  df <- filter_gear(df, single_guild_df)
}

baseHRs <- F_calc_func(model, results)

newmodel <- model

newmodel$data$fleet.model$gear_mult <- new_gear_mults
results <- e2e_run(model,nyears=3)
newHRs <- F_calc_func(newmodel, results)
print(df)
print(newHRs$Whole_domain_harvest_ratio)



```

```{r results = 'hide'}

```

```{r include=FALSE}

Activity_Finished = c()

df <- extract_nonzero_power(Power)

repeat {
  single_guild_df <- extract_single_guild_occurrence(df)

  if (nrow(single_guild_df) == 0) {
    break
  }
  
  Activity_Finished <- c(Activity_Finished, single_guild_df$Gear)
  new_gear_mults <- edit_single_activity_multiplier(single_guild_df, Target_Harvest_Ratio, Harvest_Ratio, Activity_Multiplier)
  Target_Harvest_Ratio <- modify_targer_HR(df, single_guild_df, Target_Harvest_Ratio, model)
  df <- filter_gear(df, single_guild_df$Gear)
}

new_gear_mults <- edit_single_activity_multiplier(single_guild_df, Target_Harvest_Ratio, Harvest_Ratio, Activity_Multiplier)



```

```{r include=FALSE}

df <- extract_nonzero_power(Power)

v <- c(3, 6, 10)
df <- filter_gear(df, v)

unique_sorted <- sort(unique(df$Gear))
matrix = find_simultaneous_equations(df)
matrix <- matrix[-nrow(matrix), ]
print(matrix)
newHRs <- F_calc_func(model, results)
vector <- Target_Harvest_Ratio
vector <- vector[-length(vector)]
print(vector)
x <- solve(matrix, vector)

Activity_Multiplier[unique_sorted] <- x
Activity_Multiplier[3] <- 0
Activity_Multiplier[6] <- 0
Activity_Multiplier[10] <- 0


newmodel <- model

newmodel$data$fleet.model$gear_mult <- Activity_Multiplier
results <- e2e_run(model,nyears=3)
newHRs <- F_calc_func(newmodel, results)


```

```{r}

df <- extract_nonzero_power(Power)

unique_sorted <- sort(unique(df$Gear))
matrix = find_simultaneous_equations(df)
matrix <- matrix[-nrow(matrix), ]
newHRs <- F_calc_func(model, results)
vector <- Target_Harvest_Ratio
vector <- vector[-length(vector)]

result <- lp(
  direction = "min",
  objective.in = rep(0, ncol(matrix)),
  const.mat = matrix,
  const.dir = rep("=", nrow(matrix)),
  const.rhs = vector,
  all.int = FALSE,
)

print(result$solution)

```

```{r results = 'hide'}

# matrix <- matrix(c(3, 2, 4,
#                    2, 1, 0),
#                  nrow = 2,
#                  byrow = TRUE)
# 
# vector <- c(2, 1)
# 
# result <- lp(
#   direction = "min",
#   objective.in = rep(0, ncol(matrix)),
#   const.mat = matrix,
#   const.dir = rep("=", nrow(matrix)),
#   const.rhs = vector,
#   all.int = FALSE
# )
# 
# print(result$solution)

```
